name: Build Varnish Cache Image

on:
  workflow_dispatch:
    inputs:
      build-tag:
        description: Release Tag
        default: ''

env:
  IMAGE_FILE: Dockerfile.v7-3-0
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAGS: ${{ github.event.inputs.build-tag }}
  IMAGE_USER: ${{ secrets.REGISTRY_USER }}
  IMAGE_PASS: ${{ secrets.REGISTRY_PASS }}
  IMAGE_REPO: coreio

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          ref: 'main'

      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ env.IMAGE_USER }}
          password: ${{ env.IMAGE_PASS }}

      - uses: docker/build-push-action@v4
        name: Build & Push Image
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: ${{ env.IMAGE_FILE }}
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }},${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest